<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>All Events Report</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            font-size: 10px;
        }
        @page {
            size: landscape;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #4CAF50;
            margin: 0;
        }
        .stats {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            padding: 10px;
            background: #f5f5f5;
        }
        .stat-box {
            text-align: center;
        }
        .stat-value {
            font-size: 16px;
            font-weight: bold;
            color: #4CAF50;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background: #4CAF50;
            color: white;
        }
        .footer {
            text-align: center;
            font-size: 10px;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>EVENTS REPORT</h1>
        <p>Generated on {{ date('d F Y H:i:s') }}</p>
    </div>

    <div class="stats">
        <div class="stat-box">
            <div class="stat-value">{{ $totalEvents }}</div>
            <div>Total Events</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ $upcomingCount }}</div>
            <div>Upcoming</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ $ongoingCount }}</div>
            <div>Ongoing</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ $finishedCount }}</div>
            <div>Finished</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ number_format($totalParticipants) }}</div>
            <div>Total Participants</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">Rp {{ number_format($totalRevenue, 0, ',', '.') }}</div>
            <div>Total Revenue</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Title</th>
                <th>Category</th>
                <th>Date</th>
                <th>Location</th>
                <th>Price</th>
                <th>Quota</th>
                <th>Registered</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($events as $index => $event)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $event->title }}</td>
                <td>{{ $event->category->name ?? '-' }}</td>
                <td>{{ $event->start_date->format('d M Y') }}</td>
                <td>{{ Str::limit($event->location, 30) }}</td>
                <td>@if($event->price > 0) Rp {{ number_format($event->price, 0, ',', '.') }} @else FREE @endif</td>
                <td>{{ $event->quota }}</td>
                <td>{{ $event->orders()->count() }}</td>
                <td>
                    @if($event->status == 'upcoming') Upcoming
                    @elseif($event->status == 'ongoing') Ongoing
                    @else Finished @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is an official document generated by SH3 Event Management System</p>
    </div>
</body>
</html>