<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>All Orders Report</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            font-size: 10px;
            margin: 20px;
        }
        @page {
            size: landscape;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #4CAF50;
            padding-bottom: 10px;
        }
        .header h1 {
            color: #4CAF50;
            margin: 0;
        }
        .stats {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            padding: 10px;
            background: #f5f5f5;
        }
        .stat-box {
            text-align: center;
        }
        .stat-value {
            font-size: 16px;
            font-weight: bold;
            color: #4CAF50;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background: #4CAF50;
            color: white;
        }
        .footer {
            text-align: center;
            font-size: 10px;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>ALL ORDERS REPORT</h1>
        <p>Generated on {{ date('d F Y H:i:s') }}</p>
    </div>

    <div class="stats">
        <div class="stat-box">
            <div class="stat-value">{{ $totalOrders }}</div>
            <div>Total Orders</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">Rp {{ number_format($totalRevenue, 0, ',', '.') }}</div>
            <div>Total Revenue</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Invoice</th>
                <th>Participant</th>
                <th>Event</th>
                <th>Ticket Code</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($orders as $order)
            <tr>
                <td>{{ $order->invoice_number }}</td>
                <td>{{ $order->participant->name ?? 'N/A' }}</td>
                <td>{{ $order->event->title ?? 'N/A' }}</td>
                <td>{{ $order->ticket_code }}</td>
                <td>@if($order->total_price > 0) Rp {{ number_format($order->total_price, 0, ',', '.') }} @else FREE @endif</td>
                <td>{{ ucfirst($order->status) }}</td>
                <td>{{ $order->created_at->format('d M Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is an official document generated by SH3 Event Management System</p>
    </div>
</body>
</html>