<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>All Participants Report</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            font-size: 10px;
        }
        @page {
            size: landscape;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #4CAF50;
            margin: 0;
        }
        .stats {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            padding: 10px;
            background: #f5f5f5;
        }
        .stat-box {
            text-align: center;
        }
        .stat-value {
            font-size: 18px;
            font-weight: bold;
            color: #4CAF50;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background: #4CAF50;
            color: white;
        }
        .footer {
            text-align: center;
            font-size: 10px;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>PARTICIPANTS REPORT</h1>
        <p>Generated on {{ date('d F Y H:i:s') }}</p>
    </div>

    <div class="stats">
        <div class="stat-box">
            <div class="stat-value">{{ $totalParticipants }}</div>
            <div>Total Participants</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ $activeCount }}</div>
            <div>Active</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ $inactiveCount }}</div>
            <div>Inactive</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ $maleCount }}</div>
            <div>Male</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ $femaleCount }}</div>
            <div>Female</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Hash ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Gender</th>
                <th>Birthdate</th>
                <th>Status</th>
                <th>Registered Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($participants as $index => $p)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td><strong>{{ $p->hash_id }}</strong></td>
                <td>{{ $p->name }}</td>
                <td>{{ $p->email }}</td>
                <td>{{ $p->phone }}</td>
                <td>{{ ucfirst($p->gender) }}</td>
                <td>{{ $p->birthdate->format('d M Y') }}</td>
                <td>{{ ucfirst($p->status) }}</td>
                <td>{{ $p->created_at->format('d M Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is an official document generated by SH3 Event Management System</p>
    </div>
</body>
</html>